### ISSUE TITLE
Last Updated Version Adaptation Issues

### ISSUE THREAD

**Issue by ouyanmao** [scauligi/refried#14]
Hello, may I ask which versions of Python3 and fava were the latest update compatible with? I'm using fava==1.24.4, Beancount==2.3.5, and either Python 3.10.13 or Python 3.11.5.

When I use the plugin "refried.plugins.rebudget" with the following configuration:

```
plugin "refried.plugins.rebudget"
2023-06-01 custom "fava-extension" "refried.extensions.avail_ext"
```

The plug-in cannot be activated normally, and the error message is as follows:

```BASH
Error importing "refried.plugins.rebudget": Traceback (most recent call last):
    File "/usr/local/lib/python3.10/dist-packages/beancount/loader.py", line 574, in run_transformations
      module = importlib.import_module(plugin_name)
    File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
  ModuleNotFoundError: No module named 'refried'
----------------------------------------------------------------------------------------
Importing module "refried.extensions.avail_ext" failed.
Error: "No module named 'refried'"
```

Can you tell me which specific version of fava, beancount, and python3 can work properly? (Because I couldn’t find relevant information in all the documents in the github repository) Thank you

**Comment by ouyanmao** [comment]
Thank you, after a morning of testing, I have successfully run refried version 0.7.0 on the WSL2 platform python=3.10.12, fava=1.24.4, version. I hope this information is helpful to future users.

**Comment by scauligi** [comment]
What ended up being the fix? Seems like there was some issue with the package installation?

**Comment by ouyanfen** [comment]
Hi, The problem has been solved. In the Ubuntu 22.02 system of WSL2 (Windows10 LTSC 2021), some python3 versions cannot be installed refried. My test results are that python 3.10.12 can be installed and run normally.
