### ISSUE TITLE
refried.plugins.clearing is not working

### ISSUE THREAD

**Issue by ouyanfen** [scauligi/refried#15]
Hi, I installed the refried plugin under ubuntu OS without any error throughout, but the refried.plugins.clearing plugin doesn't work, I can see the report "Account" and "Joural" on the fava page but clicking on them is not effective and gives an error. In python 3.9.18 and python 3.10.13 both show the same error message. 

Python=3.9.18，beancount=2.3.5,  fava=1.24.4;

```BASH
Exception on /beancount/extension/JournalExt/ [GET]
Traceback (most recent call last):
  File "/home/bm/miniconda3/envs/af/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bm/miniconda3/envs/af/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bm/miniconda3/envs/af/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bm/miniconda3/envs/af/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bm/miniconda3/envs/af/lib/python3.9/site-packages/fava/application.py", line 370, in extension_report
    content = Markup(render_template_string(template, extension=extension))
  File "/home/bm/miniconda3/envs/af/lib/python3.9/site-packages/flask/templating.py", line 162, in render_template_string
    template = app.jinja_env.from_string(source)
  File "/home/bm/miniconda3/envs/af/lib/python3.9/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/bm/miniconda3/envs/af/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/bm/miniconda3/envs/af/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 147, in template
jinja2.exceptions.TemplateAssertionError: No filter named 'meta_items'.
```

Python 3.10.13，beancount=2.3.5,  fava=1.24.4;

```BASH
terminal show this error:
Exception on /beancount/extension/JournalExt/ [GET]
Traceback (most recent call last):
  File "/home/bm/miniconda3/envs/ba/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bm/miniconda3/envs/ba/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bm/miniconda3/envs/ba/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bm/miniconda3/envs/ba/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bm/miniconda3/envs/ba/lib/python3.10/site-packages/fava/application.py", line 370, in extension_report
    content = Markup(render_template_string(template, extension=extension))
  File "/home/bm/miniconda3/envs/ba/lib/python3.10/site-packages/flask/templating.py", line 162, in render_template_string
    template = app.jinja_env.from_string(source)
  File "/home/bm/miniconda3/envs/ba/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/bm/miniconda3/envs/ba/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/bm/miniconda3/envs/ba/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 147, in template
jinja2.exceptions.TemplateAssertionError: No filter named 'meta_items'.
```

When I click the "Accounts" button on the left side,show Error in the upper right corner of the Fava page.

```BASH
Loading http://localhost:50000/beancount/extension/AcctsExt/ failed: <!doctype html> <html lang=en> <title>404 Not Found</title> <h1>Not Found</h1> <p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```

When I click the "Journal" button on the left side,show Error in the upper right corner of the Fava page.

```BASH
Loading http://localhost:50000/beancount/extension/JournalExt/ failed: <!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

Can you help me see where the problem is?  Here is my ledger test.bean. Thanks! 

[test.bean.zip](https://github.com/scauligi/refried/files/12775158/test.bean.zip)

<img width="835" alt="IMG_20231001_005629" src="https://github.com/scauligi/refried/assets/46487375/e653ccb9-2230-47df-9830-9a891e0c711d">

<img width="350" alt="IMG_20230930_194357" src="https://github.com/scauligi/refried/assets/46487375/c60c61a5-2fed-4a57-a9c7-e994b0ba0b84">

**Comment by scauligi** [comment]
Ahh, looks like the `meta_items` filter was added to fava in commit 63af9b5a. Upgrading fava to 1.25 should fix this.

**Comment by ouyanfen** [comment]
> Ahh, looks like the `meta_items` filter was added to fava in commit 63af9b5a. Upgrading fava to 1.25 should fix this.

Hi, thanks for your help. After switching to fava=1.2.5 version, the reports "Account" and "Journal" are working fine; but budget is not working. show these error message:

```BASH
Starting Fava on http://127.0.0.1:50000
Exception on /beancount/extension/AvailExt/ [GET]
Traceback (most recent call last):
  File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/fava/application.py", line 327, in extension_report
    content = Markup(render_template_string(template, extension=ext))
  File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/flask/templating.py", line 163, in render_template_string
    return _render(app, template, context)
  File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 57, in top-level template code
  File "/home/bm/refried/refried/extensions/avail_ext/__init__.py", line 35, in make_table
    self.ledger.all_root_account.get('Income'),
AttributeError: 'FavaLedger' object has no attribute 'all_root_account'
```

fava show these error message:
```BASH
Loading http://localhost:50000/beancount/extension/AvailExt/ failed: <!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```
thank u.

**Comment by ouyanmao** [comment]
> > Ahh, looks like the `meta_items` filter was added to fava in commit 63af9b5a. Upgrading fava to 1.25 should fix this.
> 
> Hi, thanks for your help. After switching to fava=1.2.5 version, the reports "Account" and "Journal" are working fine; but budget is not working. show these error message:
> 
> ```shell
> Starting Fava on http://127.0.0.1:50000
> Exception on /beancount/extension/AvailExt/ [GET]
> Traceback (most recent call last):
>   File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/fava/application.py", line 327, in extension_report
>     content = Markup(render_template_string(template, extension=ext))
>   File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/flask/templating.py", line 163, in render_template_string
>     return _render(app, template, context)
>   File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
>     rv = template.render(context)
>   File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
>     self.environment.handle_exception()
>   File "/home/bm/miniconda3/envs/2/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
>     raise rewrite_traceback_stack(source=source)
>   File "<template>", line 57, in top-level template code
>   File "/home/bm/refried/refried/extensions/avail_ext/__init__.py", line 35, in make_table
>     self.ledger.all_root_account.get('Income'),
> AttributeError: 'FavaLedger' object has no attribute 'all_root_account'
> ```
> 
> fava show these error message:
> 
> ```shell
> Loading http://localhost:50000/beancount/extension/AvailExt/ failed: <!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
> ```
> 
> thank u.

the same to you
